project isatidv {
    note: "This is the database schmeas , and we use aiosqlite for now while a possible migration to Postgres is planned."
}

table users {
    id integer [pk, increment]
    username text [unique, not null]
    email text [unique, not null]
    hashed_password text [not null]
    is_admin boolean [default: false, not null]
    is_active boolean [default: true, not null]
    created_at timestamp [default: `CURRENT_TIMESTAMP`, not null]
    updated_at timestamp [default: `CURRENT_TIMESTAMP`, not null]
}

table sessions {
    id integer [pk, increment]
    user_id integer [not null, ref: > users.id]
    session_id text [unique, not null]
    refresh_token_hash text [not null]
    is_revoked boolean [default: false, not null]
    revoked_at timestamp [null]
    expires_at timestamp [not null]
    last_activity_at timestamp [null]
    ip_address text [null]
    user_agent text [null]
    created_at timestamp [default: `CURRENT_TIMESTAMP`, not null]
    updated_at timestamp [default: `CURRENT_TIMESTAMP`, not null]
}

table servers {
    id integer [pk, increment]
    name text [not null]
    ip_address text [not null]
    port integer [not null]
    is_active boolean [default: true, not null]
    created_at timestamp [default: `CURRENT_TIMESTAMP`, not null]
    updated_at timestamp [default: `CURRENT_TIMESTAMP`, not null]
}
